export const skills = [
  { slug: "js", icon: "/javascript.svg" },
  { slug: "ts", icon: "/typescript.svg" },
  { slug: "react", icon: "/react.svg" },
  { slug: "android", icon: "/android.svg" },
  { slug: "ios", icon: "/ios.svg" },
  { slug: "firebase", icon: "/firebase.svg" },
  { slug: "fastlane", icon: "/fastlane.svg" },
  { slug: "html", icon: "/html.svg" },
  { slug: "css", icon: "/css.svg" },
  { slug: "tailwind", icon: "/tailwind.svg" },
  { slug: "nextjs", icon: "/nextjs.svg" },
  { slug: "graphql", icon: "/graphql.svg" },
  { slug: "redux", icon: "/redux.svg" },
  { slug: "nodejs", icon: "/nodejs.svg" },
  { slug: "sentry", icon: "/sentry.svg" },
  { slug: "docker", icon: "/docker.svg" },
];
